### ISSUE TITLE
Version 0.41 Not working with docker-machine

### ISSUE THREAD

**Issue by marcofranssen** [Microsoft/DockerToolsDocs#13]
It gives me following error. Most probably because it has not ran the command "docker-machine env".

**How can I specify it should connect to one of my docker-machines?**

The add docker support menu item only adds some Dockerfile and docker-compose*.yml.

Previously it also added a Dockertasks.ps1.

**Code:**
MSB4018	Line

**Description:**
The "PrepareForCompile" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22name%22%3A%7B%22productapi_productapi%22%3Atrue%7D%7D&limit=1: open //./pipe/docker_engine: The system cannot find the file specified.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.PrepareForCompile.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

**File:**
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing\ImportAfter\Microsoft.DotNet.Docker.targets	61

**Comment by weidazhao** [comment]
docker-machine is not supported since Docker Tools 0.40. Please install [Docker for Windows](https://www.docker.com/products/docker#/windows) to make Docker Tools 0.40+ work.

**Comment by marcofranssen** [comment]
Is there any intention to support it again in the future? docker-machine gives me more flexibility with regards to where the machine is ran... For example on azure.

**Comment by weidazhao** [comment]
The latest Docker Tools relies on volume mapping to work in order to improve the performance of local development and debugging experience in Visual Studio, which is critical to local development experience with Docker. This is not possible when Docker runs on a separate machine. We are focused on delivering the best experience of Docker Tools with Docker for Windows at the moment.
